//! Shell providers. Each supported shell implements this Provider
//! interface in a file under `provider/` and registers itself here.
//!
//! The interface is a plain struct of function pointers (lightweight
//! vtable). Adding a new shell is: write `provider/xyz.zig` exporting
//! `pub const provider: Provider = .{ ... }`, then add it to `all` below.
//! The comptime struct-literal check ensures every provider fills in
//! every required field — that's the "runtime features" guarantee.

const std = @import("std");

pub const Shell = enum {
    bash,
    zsh,
    fish,
    nushell,

    pub fn displayName(self: Shell) []const u8 {
        return switch (self) {
            .bash => "bash",
            .zsh => "zsh",
            .fish => "fish",
            .nushell => "nushell",
        };
    }

    /// Infer a shell from a `$SHELL` path or a bare name ("/bin/zsh", "fish", …).
    pub fn fromPath(path: []const u8) ?Shell {
        const basename = std.fs.path.basename(path);
        if (std.mem.eql(u8, basename, "bash")) return .bash;
        if (std.mem.eql(u8, basename, "zsh")) return .zsh;
        if (std.mem.eql(u8, basename, "fish")) return .fish;
        if (std.mem.eql(u8, basename, "nu")) return .nushell;
        if (std.mem.eql(u8, basename, "nushell")) return .nushell;
        return null;
    }
};

pub const Env = struct {
    key: []const u8,
    value: []const u8,
};

pub const Provider = struct {
    shell: Shell,
    /// File extension including the leading dot, e.g. ".sh", ".fish", ".nu".
    file_extension: []const u8,

    /// Emit a single exported binding for one env var, terminated with a newline.
    writeExportFn: *const fn (w: *std.Io.Writer, env: Env) std.Io.Writer.Error!void,

    /// Emit the one-line "source this file from your rc" hint (no trailing newline).
    writeSourceCommandFn: *const fn (w: *std.Io.Writer, path: []const u8) std.Io.Writer.Error!void,

    pub fn writeExport(self: Provider, w: *std.Io.Writer, env: Env) !void {
        return self.writeExportFn(w, env);
    }

    pub fn writeSourceCommand(self: Provider, w: *std.Io.Writer, path: []const u8) !void {
        return self.writeSourceCommandFn(w, path);
    }

    /// Write a complete env file: a header comment followed by one export per env.
    pub fn writeFile(self: Provider, w: *std.Io.Writer, envs: []const Env) !void {
        try w.writeAll("# Generated by insh. Do not edit — run `insh sync` to refresh.\n");
        for (envs) |e| try self.writeExport(w, e);
    }
};

const bash_provider = @import("provider/bash.zig");
const zsh_provider = @import("provider/zsh.zig");
const fish_provider = @import("provider/fish.zig");
const nushell_provider = @import("provider/nushell.zig");

/// All supported providers. Order is stable; callers may iterate to write
/// one env file per shell.
pub const all = [_]Provider{
    bash_provider.provider,
    zsh_provider.provider,
    fish_provider.provider,
    nushell_provider.provider,
};

pub fn byShell(s: Shell) Provider {
    return switch (s) {
        .bash => bash_provider.provider,
        .zsh => zsh_provider.provider,
        .fish => fish_provider.provider,
        .nushell => nushell_provider.provider,
    };
}

test "Shell.fromPath detects common shells" {
    try std.testing.expectEqual(@as(?Shell, .bash), Shell.fromPath("/bin/bash"));
    try std.testing.expectEqual(@as(?Shell, .zsh), Shell.fromPath("/usr/bin/zsh"));
    try std.testing.expectEqual(@as(?Shell, .fish), Shell.fromPath("/opt/homebrew/bin/fish"));
    try std.testing.expectEqual(@as(?Shell, .nushell), Shell.fromPath("/opt/homebrew/bin/nu"));
    try std.testing.expectEqual(@as(?Shell, .nushell), Shell.fromPath("nushell"));
    try std.testing.expectEqual(@as(?Shell, null), Shell.fromPath("/bin/sh"));
}

test "all providers have distinct shells and extensions" {
    var seen_shell: [4]bool = @splat(false);
    for (all) |p| {
        const idx = @intFromEnum(p.shell);
        try std.testing.expect(!seen_shell[idx]);
        seen_shell[idx] = true;
        try std.testing.expect(p.file_extension.len > 1);
        try std.testing.expectEqual(@as(u8, '.'), p.file_extension[0]);
    }
    for (seen_shell) |s| try std.testing.expect(s);
}

test "writeFile integration — every provider emits a header and one line per env" {
    const gpa = std.testing.allocator;
    const envs = [_]Env{
        .{ .key = "A", .value = "one" },
        .{ .key = "B", .value = "two" },
    };
    for (all) |p| {
        var aw: std.Io.Writer.Allocating = .init(gpa);
        defer aw.deinit();
        try p.writeFile(&aw.writer, &envs);
        const out = aw.writer.buffered();

        // Every provider starts with a comment line (all four shells use `#`).
        try std.testing.expect(std.mem.startsWith(u8, out, "#"));
        // One newline for the header + one for each env binding.
        var newlines: usize = 0;
        for (out) |c| if (c == '\n') {
            newlines += 1;
        };
        try std.testing.expectEqual(@as(usize, 1 + envs.len), newlines);
        // The plaintext key name must appear verbatim in the output.
        try std.testing.expect(std.mem.indexOf(u8, out, "A") != null);
        try std.testing.expect(std.mem.indexOf(u8, out, "B") != null);
        // The plaintext value must appear verbatim for these quote-safe values.
        try std.testing.expect(std.mem.indexOf(u8, out, "one") != null);
        try std.testing.expect(std.mem.indexOf(u8, out, "two") != null);
    }
}
